{{- if not .Values.cron.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "github-secret-synchronizer.fullname" . }}
  labels:
    {{- include "github-secret-synchronizer.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "github-secret-synchronizer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ include "github-secret-synchronizer.fullname" . }}
          env:
            {{- include "github-secret-synchronizer.github-env" . | nindent 12 }}
            {{- if .Values.synchronizer.json.enabled }}
            {{- include "github-secret-synchronizer.json-env" . | nindent 12 }}
            {{- else if .Values.synchronizer.yaml.enabled }}
            {{- include "github-secret-synchronizer.yaml-env" .| nindent 12 }}
            {{- else if .Values.synchronizer.azure.enabled }}
            {{- include "github-secret-synchronizer.azure-env" . | nindent 12 }}
            {{- else if .Values.synchronizer.aws.enabled }}
            {{- include "github-secret-synchronizer.aws-env" . | nindent 12 }}
            {{- end }}
            {{- include "github-secret-synchronizer.defaults" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.synchronizer.json.enabled }}
            {{- include "github-secret-synchronizer.json-volumeMount" . | nindent 12 }}
            {{- else if .Values.synchronizer.yaml.enabled }}
            {{- include "github-secret-synchronizer.yaml-volumeMount" . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.synchronizer.json.enabled }}
        {{- include "github-secret-synchronizer.json-volume" . | nindent 8 }}
        {{- else if .Values.synchronizer.yaml.enabled }}
        {{- include "github-secret-synchronizer.yaml-volume" . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
