{{- if not .Values.github.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-secret-synchronizer.fullname" . }}-github
  labels:
    {{- include "github-secret-synchronizer.labels" . | nindent 4 }}
stringData:
  appID: {{ .Values.github.appID | quote }}
  appInstallationID: {{ .Values.github.appInstallationID | quote }}
  appPrivateKey: {{ .Values.github.appPrivateKey | quote }}
  organization: {{ .Values.github.organization }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-secret-synchronizer.fullname" . }}-vault
  labels:
    {{- include "github-secret-synchronizer.labels" . | nindent 4 }}
stringData:
  {{- if .Values.synchronizer.json.enabled }}
  secrets.json: |
    {{ .Values.synchronizer.json.data | toJson }}
  {{- end }}
  {{- if .Values.synchronizer.yaml.enabled }}
  secrets.yaml: |
    {{ .Values.synchronizer.yaml.data | toYaml }}
  {{- end }}
  {{- if and (eq .Values.synchronizer.azure.enabled true) (not .Values.synchronizer.azure.existingSecretName) }}
  keyvaultURL: {{ .Values.synchronizer.azure.keyvaultURL | quote }}
  clientID: {{ .Values.synchronizer.azure.clientID | quote }}
  tenantID: {{ .Values.synchronizer.azure.tenantID | quote }}
  clientSecret: {{ .Values.synchronizer.azure.clientSecret | quote }}
  {{- end }}
  {{- if and (eq .Values.synchronizer.aws.enabled true) (not .Values.synchronizer.aws.existingSecretName) }}
  accessKeyID: {{ .Values.synchronizer.aws.accessKeyID | quote }}
  secretAccessKey: {{ .Values.synchronizer.aws.secretAccessKey | quote }}
  region: {{ .Values.synchronizer.aws.region | quote }}
  {{- end }}

