---
name: CI Build

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - charts/**

env:
  GOLANG_VERSION: '1.23.4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    name: Filter changes
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      chart: ${{ steps.filter.outputs.chart }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
            chart:
              - 'charts/github-secret-synchronizer/Chart.yaml'
              - 'charts/ingress-nginx/**/*'
  check-go:
    if: ${{ needs.changes.outputs.go == 'true' }}
    name: Ensure Go modules synchronicity
    runs-on: ubuntu-24.04
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Golang
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Download all Go modules
        run: |
          go mod download

      - name: Check for tidiness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .

  lint-go:
    if: ${{ needs.changes.outputs.go == 'true' }}
    name: Lint Go code
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Golang
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          # renovate: datasource=go packageName=github.com/golangci/golangci-lint versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)?$
          version: v1.63.4
          args: --verbose

  test-go:
    if: ${{ needs.changes.outputs.go == 'true' }}
    name: Test Go code
    runs-on: ubuntu-24.04
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Golang
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Run tests
        run: go test -v ./...

  chart-lint:
    if: ${{ needs.changes.outputs.chart == 'true' }}
    name: Lint Helm chart
    runs-on: ubuntu-24.04
    needs: changes
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm Docs
        uses: gabe565/setup-helm-docs-action@d5c35bdc9133cfbea3b671acadf50a29029e87c2 # v1.0.4

      - name: Set up Helm Chart Testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Lint chart
        run: ct lint

      - name: Check docs
        run: |
          helm-docs --chart-search-root charts
          git diff --exit-code charts/github-secret-synchronizer/README.md
